# -*- coding: utf-8 -*-
"""Content data for Alexander Kucherov's bilingual personal site."""

ICONS = {
    "compass": '<circle cx="12" cy="12" r="9"/><polygon points="15,9 12.6,12.6 9,15 11.4,11.4"/>',
    "network": '<circle cx="6" cy="6" r="2.1"/><circle cx="18" cy="6" r="2.1"/><circle cx="12" cy="18" r="2.1"/><line x1="7.6" y1="7.4" x2="10.6" y2="16"/><line x1="16.4" y1="7.4" x2="13.4" y2="16"/><line x1="8.1" y1="6" x2="15.9" y2="6"/>',
    "clipboard-check": '<rect x="6" y="4" width="12" height="17" rx="2"/><path d="M9 4V3.5a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1V4"/><path d="M8.7 12.8l2 2 4-4.2"/>',
    "cpu": '<rect x="8" y="8" width="8" height="8" rx="1"/><rect x="10.5" y="10.5" width="3" height="3"/><line x1="8" y1="4" x2="8" y2="7"/><line x1="16" y1="4" x2="16" y2="7"/><line x1="8" y1="17" x2="8" y2="20"/><line x1="16" y1="17" x2="16" y2="20"/><line x1="4" y1="8" x2="7" y2="8"/><line x1="4" y1="16" x2="7" y2="16"/><line x1="17" y1="8" x2="20" y2="8"/><line x1="17" y1="16" x2="20" y2="16"/>',
    "bar-chart": '<line x1="5" y1="21" x2="5" y2="12"/><line x1="12" y1="21" x2="12" y2="7"/><line x1="19" y1="21" x2="19" y2="15"/><line x1="3" y1="21" x2="21" y2="21"/>',
    "users": '<circle cx="9" cy="8.2" r="3"/><path d="M3.3 20c0-3.4 2.6-6 5.7-6s5.7 2.6 5.7 6"/><circle cx="17.2" cy="9.5" r="2.3"/><path d="M15.6 14.4c2.5.4 4.4 2.6 4.4 5.3"/>',
    "target": '<circle cx="12" cy="12" r="8.2"/><circle cx="12" cy="12" r="4.6"/><circle cx="12" cy="12" r="1"/>',
    "rocket": '<path d="M12 2.5c2.8 1.9 4.6 5.7 4.1 10L14 14.6H10L7.9 12.5c-.5-4.3 1.3-8.1 4.1-10z"/><circle cx="12" cy="8.7" r="1.5"/><path d="M9.3 14.6l-2.1 4.6"/><path d="M14.7 14.6l2.1 4.6"/><path d="M10 14.6l-.5 4.4 2.5-1.8 2.5 1.8-.5-4.4"/>',
    "flag": '<line x1="6" y1="21" x2="6" y2="3.5"/><path d="M6 4.5c3-1.3 5 1.3 8 0v9c-3 1.3-5-1.3-8 0z"/>',
    "wrench": '<path d="M14.7 3.6a4.2 4.2 0 0 0-5.6 5.2L4 13.9v3.1h3.1l5.1-5.1a4.2 4.2 0 0 0 5.2-5.6l-2.8 2.8-2.1-2.1z"/>',
    "browser": '<rect x="3.5" y="4.5" width="17" height="15" rx="2"/><line x1="3.5" y1="8.5" x2="20.5" y2="8.5"/><circle cx="6.2" cy="6.5" r="0.6" fill="currentColor" stroke="none"/><circle cx="8.1" cy="6.5" r="0.6" fill="currentColor" stroke="none"/>',
    "presentation": '<rect x="3.5" y="4.5" width="17" height="11" rx="1.5"/><path d="M8.5 20l1.5-4.5h4l1.5 4.5"/><line x1="12" y1="15.5" x2="12" y2="18.3"/><path d="M7.5 12.5l2.5-3 2 2 3.5-4"/>',
    "file-text": '<path d="M7 3.5h7l3.5 3.5v13.5H7z"/><path d="M14 3.5V7h3.5"/><line x1="9.3" y1="12" x2="14.7" y2="12"/><line x1="9.3" y1="15.3" x2="14.7" y2="15.3"/><line x1="9.3" y1="18.6" x2="12.5" y2="18.6"/>',
    "grid": '<rect x="4" y="4" width="7" height="7" rx="1"/><rect x="13" y="4" width="7" height="7" rx="1"/><rect x="4" y="13" width="7" height="7" rx="1"/><rect x="13" y="13" width="7" height="7" rx="1"/>',
    "pen": '<path d="M5 19.5l1-4L15.5 5.9a1.7 1.7 0 0 1 2.4 0l0.2.2a1.7 1.7 0 0 1 0 2.4L8.6 18.9z"/><line x1="14" y1="7.5" x2="16.6" y2="10.1"/><line x1="5" y1="19.5" x2="9" y2="18.5"/>',
    "search": '<circle cx="10.8" cy="10.8" r="6.3"/><line x1="15.4" y1="15.4" x2="20" y2="20"/>',
    "briefcase": '<rect x="3.5" y="7.5" width="17" height="12" rx="2"/><path d="M8.5 7.5V6a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v1.5"/><line x1="3.5" y1="13" x2="20.5" y2="13"/>',
    "handshake": '<path d="M3.5 12.5l3.2-3.2 2.8 1.6 2-2 2.6 2.6-2 2 3.3 3.3-2 2-3.3-3.3-2 2-4.6-4z"/><path d="M12.5 8.9l2.6-2.6 3.4 3.4-2.6 2.6"/>',
}

NAV = [
    ("about", "About", "О себе"),
    ("expertise", "Expertise", "Экспертиза"),
    ("services", "Services", "Услуги"),
    ("products", "Products", "Продукты"),
    ("experience", "Experience", "Опыт"),
    ("case-studies", "Case Studies", "Кейсы"),
]

EXPERTISE = [
    ("clipboard-check", "Project & Program Management", "Управление проектами и программами",
     "Structuring complex, cross-functional initiatives so scope, budget, risk and milestones stay under control from kickoff to delivery.",
     "Структурирую сложные кросс-функциональные инициативы так, чтобы объём работ, бюджет, риски и сроки оставались под контролем от старта до сдачи."),
    ("compass", "Digital Transformation", "Цифровая трансформация",
     "Turning manual, fragmented operations into connected digital processes — from current-state assessment to a working roadmap.",
     "Превращаю ручные разрозненные процессы в связанные цифровые — от анализа текущего состояния до рабочей дорожной карты."),
    ("bar-chart", "Business Process Optimisation", "Оптимизация бизнес-процессов",
     "Mapping how work actually happens, removing bottlenecks, and redesigning SOPs so operations scale without adding headcount.",
     "Картирую реальные процессы, устраняю узкие места и пересобираю регламенты так, чтобы операции масштабировались без роста штата."),
    ("grid", "CRM / ERP Implementation", "Внедрение CRM / ERP",
     "Translating business needs into requirements, user stories and acceptance criteria that engineering and vendor teams can build against.",
     "Перевожу потребности бизнеса в требования, user stories и критерии приёмки, по которым могут работать разработчики и подрядчики."),
    ("cpu", "AI & Business Automation", "AI и автоматизация бизнеса",
     "Identifying where AI and automation genuinely remove manual work, and structuring those opportunities into requirements for implementation teams.",
     "Нахожу, где AI и автоматизация реально снимают ручной труд, и превращаю это в требования для команд внедрения."),
    ("search", "Business Analysis & Requirements", "Бизнес-анализ и требования",
     "Gathering and documenting business requirements that hold up under real engineering scrutiny — the bridge between the business and IT.",
     "Собираю и документирую требования, которые выдерживают проверку инженерами, — мост между бизнесом и IT."),
    ("network", "Operations Transformation", "Трансформация операций",
     "Building operational infrastructure and service delivery capability from the ground up, including call-centre and field operations.",
     "Строю операционную инфраструктуру и сервисную доставку с нуля, включая контакт-центры и полевые операции."),
    ("bar-chart", "Sales Operations", "Управление продажами (Sales Ops)",
     "Designing the sales processes, reporting and quality metrics that turn ad-hoc selling into a predictable, measurable engine.",
     "Проектирую процессы продаж, отчётность и метрики качества, превращая хаотичные продажи в предсказуемую систему."),
    ("flag", "Change Management", "Управление изменениями",
     "Bringing regional teams, partners and vendors along through large-scale change, with training and performance management built in.",
     "Провожу региональные команды, партнёров и подрядчиков через масштабные изменения — с обучением и управлением эффективностью."),
    ("target", "KPI / OKR Systems", "Системы KPI / OKR",
     "Defining the metrics that matter and the governance cadence that keeps teams accountable to milestones, budget and quality.",
     "Определяю метрики, которые действительно важны, и ритм управления, который держит команды в ответственности за сроки, бюджет и качество."),
    ("users", "Cross-functional Leadership", "Кросс-функциональное лидерство",
     "Coordinating sales, marketing, operations and technology teams around a single roadmap and a single set of priorities.",
     "Координирую продажи, маркетинг, операции и технологии вокруг единой дорожной карты и единых приоритетов."),
    ("handshake", "Vendor & Stakeholder Management", "Управление подрядчиками и стейкхолдерами",
     "Managing external partners and internal stakeholders so delivery stays aligned, on budget and on schedule.",
     "Управляю внешними партнёрами и внутренними стейкхолдерами, чтобы результат оставался согласованным, в бюджете и в срок."),
]

# icon, title_en, title_ru, for_en, for_ru, items[(en,ru)], data_service, wide(bool)
SERVICES = [
    ("compass", "Digital Transformation Advisory", "Консалтинг по цифровой трансформации",
     "For companies that need to redesign processes, systems and operating models.",
     "Для компаний, которым нужно пересобрать процессы, системы и операционную модель.",
     [("Current-state assessment", "Анализ текущего состояния"),
      ("Transformation roadmap", "Дорожная карта трансформации"),
      ("Process redesign", "Пересборка процессов"),
      ("CRM/ERP requirements", "Требования к CRM/ERP"),
      ("Implementation governance", "Управление внедрением"),
      ("KPI framework", "Система KPI")],
     "Digital Transformation Advisory", False),
    ("clipboard-check", "Project & Program Management", "Управление проектами и программами",
     "For complex, cross-functional initiatives that need structured delivery.",
     "Для сложных кросс-функциональных инициатив, которым нужна структурированная реализация.",
     [("Project setup", "Запуск проекта"),
      ("Roadmap & milestones", "Дорожная карта и вехи"),
      ("Risk management", "Управление рисками"),
      ("Stakeholder governance", "Управление стейкхолдерами"),
      ("Vendor coordination", "Координация подрядчиков"),
      ("Delivery control", "Контроль реализации")],
     "Project & Program Management", False),
    ("bar-chart", "Business Process Optimisation", "Оптимизация бизнес-процессов",
     "For companies with inefficient or poorly scalable operations.",
     "Для компаний с неэффективными или плохо масштабируемыми процессами.",
     [("Process mapping", "Картирование процессов"),
      ("Bottleneck analysis", "Анализ узких мест"),
      ("SOP redesign", "Пересборка регламентов"),
      ("Automation opportunities", "Возможности автоматизации"),
      ("KPI and control system", "Система KPI и контроля")],
     "Business Process Optimisation", False),
    ("grid", "CRM / ERP & Business Requirements", "CRM/ERP и бизнес-требования",
     "For companies preparing to implement or improve digital systems.",
     "Для компаний, которые готовятся внедрить или улучшить цифровые системы.",
     [("Requirements gathering", "Сбор требований"),
      ("Business requirements documentation", "Документирование бизнес-требований"),
      ("User stories", "User stories"),
      ("Backlog creation", "Формирование бэклога"),
      ("Vendor/developer coordination", "Координация подрядчиков и разработчиков"),
      ("Acceptance criteria", "Критерии приёмки")],
     "CRM / ERP & Business Requirements", False),
    ("cpu", "AI Automation for Business", "AI-автоматизация для бизнеса",
     "Business-side guidance for identifying and structuring AI automation opportunities — not engineering implementation.",
     "Бизнес-консультирование по поиску и структурированию возможностей AI-автоматизации — без инженерной реализации.",
     [("AI opportunity assessment", "Оценка возможностей AI"),
      ("Business process automation design", "Проектирование автоматизации процессов"),
      ("AI agent use-case identification", "Поиск сценариев для AI-агентов"),
      ("Workflow redesign", "Пересборка рабочих процессов"),
      ("Requirements for implementation teams", "Требования для команд внедрения")],
     "AI Automation for Business", False),
    ("briefcase", "Executive & Management Consulting", "Консалтинг для руководителей",
     "For leaders building or scaling a department, function or commercial operation.",
     "Для руководителей, которые строят или масштабируют подразделение, функцию или коммерческую операцию.",
     [("Building departments from scratch", "Построение подразделений с нуля"),
      ("Scaling operations", "Масштабирование операций"),
      ("KPI systems", "Системы KPI"),
      ("Management processes", "Управленческие процессы"),
      ("Commercial operations", "Коммерческие операции"),
      ("Cross-functional leadership", "Кросс-функциональное лидерство")],
     "Executive & Management Consulting", False),
    ("users", "Workshops & Corporate Training", "Воркшопы и корпоративное обучение",
     "Practical training for teams and leaders, built from real operating experience.",
     "Практическое обучение для команд и руководителей, основанное на реальном операционном опыте.",
     [("Project management for business leaders", "Управление проектами для руководителей бизнеса"),
      ("Digital transformation", "Цифровая трансформация"),
      ("Process optimisation", "Оптимизация процессов"),
      ("CRM implementation", "Внедрение CRM"),
      ("KPI management", "Управление KPI"),
      ("Working effectively with IT teams", "Эффективная работа с IT-командами"),
      ("Requirements gathering for non-technical managers", "Сбор требований для нетехнических руководителей")],
     "Workshops & Corporate Training", True),
]

# groups: title_en, title_ru, items[(icon, title_en, title_ru, desc_en, desc_ru, tag_en, tag_ru)]
PRODUCT_GROUPS = [
    ("Career & International Moves", "Карьера и международные переезды", [
        ("compass", "International Job Search Playbook for Senior Leaders", "Гид по международному поиску работы для топ-менеджеров",
         "A structured approach to an international, multi-country job search — country strategy, working with agencies, and localizing your CV for each market.",
         "Структурированный подход к поиску работы сразу в нескольких странах — стратегия по гео, работа с агентствами и локализация резюме под каждый рынок.",
         "Playbook + templates", "Методика + шаблоны"),
        ("target", "Career Coaching for Your Job Search", "Карьерное консультирование по поиску работы",
         "One-on-one strategy, interview preparation and offer negotiation support from someone running the same process himself.",
         "Индивидуальная стратегия поиска, подготовка к интервью и помощь в переговорах об оффере — от человека, который сам сейчас проходит этот путь.",
         "1:1 sessions", "Личные сессии"),
        ("file-text", "CV Rewritten for One Specific Vacancy", "Резюме под конкретную вакансию",
         "Not a generic template — a CV rebuilt around one role and one market, so it actually gets past the first filter.",
         "Не универсальный шаблон, а резюме, пересобранное под конкретную вакансию и рынок — чтобы оно реально проходило первый отбор.",
         "Fixed price · 2–3 days", "Фикс. цена · 2–3 дня"),
        ("flag", "Personal / Executive Coaching", "Личный коучинг для руководителей",
         "Regular sessions focused on decisions, not just conversation — for people navigating a career pivot or a big transition.",
         "Регулярные сессии с фокусом на решениях, а не просто на разговоре — для тех, кто проходит смену карьеры или большой переход.",
         "Ongoing · monthly", "Регулярно · помесячно"),
    ]),
    ("Launching & Growing a Business", "Запуск и рост бизнеса", [
        ("network", "Playbook: Launching a Partner Network From Zero", "Плейбук запуска партнёрской сети с нуля",
         "A step-by-step method for building a dealer, franchise or service network — based on a real case that went from 0 to ~300 locations in three years.",
         "Пошаговая методика запуска дилерской, франчайзинговой или сервисной сети — на основе реального кейса: с нуля до ~300 точек за три года.",
         "Playbook + templates", "Методика + шаблоны"),
        ("users", "Building a Sales Department From Scratch", "Построение отдела продаж с нуля",
         "Structure, roles, scripts, CRM setup and a KPI system for a brand-new sales team — delivered, not just advised on.",
         "Структура, роли, скрипты, настройка CRM и система KPI для нового отдела продаж — под ключ, а не просто советы.",
         "Done-for-you", "Под ключ"),
        ("rocket", "Startup Launch Consulting", "Консультирование по запуску стартапа",
         "From idea to a working business model — team structure, core processes and the metrics that actually matter early on.",
         "От идеи до работающей бизнес-модели — структура команды, ключевые процессы и метрики, которые действительно важны на старте.",
         "Project-based", "Проектная работа"),
        ("handshake", "Investor Search & Pitch Support", "Поиск инвесторов и подготовка питча",
         "Getting your investor materials into shape and pointing you toward the right people to send them to.",
         "Приведение материалов для инвесторов в порядок и помощь в поиске подходящих контактов, кому их отправить.",
         "Fixed-price package", "Пакет с фикс. ценой"),
        ("bar-chart", "Business Plan & Financial Model", "Бизнес-план и финансовая модель",
         "A clear, defensible model for a launch, a bank loan or an investor conversation — with a real payback calculation.",
         "Понятная и защищаемая модель для запуска, кредита или разговора с инвестором — с реальным расчётом окупаемости.",
         "Fixed price · ~1 week", "Фикс. цена · ~1 неделя"),
        ("search", "Market & Competitor Analysis", "Анализ рынка и конкурентов",
         "A structured view of the market and the competition, built to support a real launch, pricing or positioning decision.",
         "Структурированный обзор рынка и конкурентов — под конкретное решение о запуске, цене или позиционировании.",
         "Fixed price · 3–5 days", "Фикс. цена · 3–5 дней"),
    ]),
    ("Operations, CRM & Data", "Операции, CRM и данные", [
        ("clipboard-check", "CRM / ERP Requirements Toolkit", "Тулкит по сбору требований для CRM/ERP",
         "Requirement-doc templates, user stories and a vendor-selection checklist — so the budget doesn't go to the wrong system.",
         "Шаблоны ТЗ, user stories и чек-лист выбора вендора — чтобы бюджет не ушёл на систему, которая не подойдёт бизнесу.",
         "Template pack", "Набор шаблонов"),
        ("bar-chart", "Sales Department Audit", "Аудит отдела продаж",
         "A review of your process, funnel, scripts and KPIs, with specific points where you're leaving revenue on the table.",
         "Разбор процесса, воронки, скриптов и KPI отдела продаж — с конкретными точками, где бизнес теряет выручку.",
         "Fixed-price audit", "Фикс. цена · аудит"),
        ("grid", "Automated Reports & Dashboards (Excel / Sheets)", "Автоматизация отчётов и дашбордов (Excel / Google Sheets)",
         "Complex spreadsheets, automatic reports and dashboards — instead of rebuilding the same report by hand every week.",
         "Сложные таблицы, автоматические отчёты и дашборды — вместо ручного сведения одного и того же отчёта каждую неделю.",
         "Fixed price · days", "Фикс. цена · дни"),
        ("file-text", "SOPs & Job Descriptions", "Регламенты и должностные инструкции",
         "Clear, written procedures so a process doesn't live only in one person's head.",
         "Понятные письменные регламенты — чтобы процесс не держался в голове одного человека.",
         "Fixed-price package", "Пакет с фикс. ценой"),
        ("users", "Hiring Process Setup", "Настройка процесса найма",
         "Job postings, a hiring funnel and interview scripts built so you hire faster and more accurately.",
         "Вакансии, воронка подбора и сценарии интервью — чтобы нанимать быстрее и точнее.",
         "Fixed-price package", "Пакет с фикс. ценой"),
    ]),
    ("Done-For-You AI Deliverables", "Готовые AI-продукты под ключ", [
        ("cpu", "AI Automation Audit", "Аудит AI-автоматизации бизнеса",
         "A fixed-price audit pinpointing exactly where AI and automation will save real time and money — with a concrete plan, not just ideas.",
         "Платный фиксированный аудит: где в бизнесе AI и автоматизация реально сэкономят время и деньги — с конкретным планом внедрения.",
         "Fixed-price audit", "Фикс. цена · аудит"),
        ("wrench", "A Specialist for One Hard Problem", "Специалист для решения одной сложной задачи",
         "One-off help for a business or an individual — untangling a messy situation and finding a workable way through it.",
         "Разовая помощь бизнесу или конкретному человеку — разобраться в запутанной ситуации и найти рабочее решение.",
         "One-off engagement", "Разовая задача"),
        ("browser", "Website, Landing Page or Product Listing", "Сайт, лендинг или карточка товара",
         "A fast, clean business-card website, landing page or marketplace listing — no developers, no long quotes.",
         "Быстрая и аккуратная сборка сайта-визитки, лендинга или карточки товара на маркетплейсе — без разработчиков и долгих смет.",
         "Fixed price · days", "Фикс. цена · дни"),
        ("presentation", "Presentation & Pitch Support", "Презентация и подготовка к защите",
         "Structure, slides and a rehearsal — for an investor pitch, a board report, or defending a project.",
         "Структура, слайды и репетиция — для питча инвесторам, отчёта совету директоров или защиты проекта.",
         "Fixed-price package", "Пакет с фикс. ценой"),
        ("pen", "Sales Copy & Commercial Proposals", "Продающие тексты и коммерческие предложения",
         "Proposals and copy that explain real value to the reader — instead of just listing features.",
         "Коммерческие предложения и тексты, которые объясняют ценность для клиента, а не просто перечисляют услуги.",
         "Fixed price · days", "Фикс. цена · дни"),
    ]),
]

NUMBERS = [
    ("flag", "20+", "20+", "Years of leadership and transformation experience", "лет опыта в лидерстве и трансформации бизнеса"),
    ("network", "300", "300", "Service centres built into a nationwide network", "сервисных центров построено в сеть федерального масштаба"),
    ("bar-chart", "RUB 100M", "100 млн ₽", "In new sales developed from zero within three years", "новых продаж с нуля за три года"),
    ("target", "28th → 2nd", "28-е → 2-е", "Global brand ranking improvement for Russia within the network", "место России в глобальном рейтинге сети"),
]

METHOD_STEPS = [
    ("Diagnose", "Диагностика", "Understand the current state — processes, systems, stakeholders and constraints — before proposing anything.",
     "Разбираюсь в текущей ситуации — процессы, системы, стейкхолдеры и ограничения — прежде чем что-либо предлагать."),
    ("Design", "Проектирование", "Define the target operating model, requirements and success metrics in terms the business and IT both understand.",
     "Определяю целевую операционную модель, требования и метрики успеха на языке, понятном и бизнесу, и IT."),
    ("Plan", "Планирование", "Build a realistic roadmap with milestones, ownership, budget and risk controls in place from day one.",
     "Строю реалистичную дорожную карту с вехами, ответственными, бюджетом и контролем рисков с первого дня."),
    ("Execute", "Реализация", "Coordinate teams, vendors and engineers to deliver against the plan, with governance to keep things on track.",
     "Координирую команды, подрядчиков и инженеров для реализации плана, с управлением, которое держит всё в графике."),
    ("Measure", "Измерение", "Put KPI and reporting structures in place so results are visible, not anecdotal.",
     "Внедряю KPI и отчётность, чтобы результат был видимым, а не на словах."),
    ("Improve", "Улучшение", "Use what the data shows to refine the process, the system and the plan — continuously, not once.",
     "Использую данные, чтобы улучшать процесс, систему и план — постоянно, а не разово."),
]

TIMELINE = [
    ("2019 – Present", "2019 – настоящее время", "Peugeot / Stellantis",
     "Head of Network Development", "Директор по развитию сети",
     "Led the end-to-end launch and nationwide expansion of the EUROREPAR Car Service network, coordinating regional managers, marketing, operations and external partners. Defined business requirements for CRM, website and lead-generation systems, and drove digital transformation initiatives across the network while managing partner onboarding, training, KPIs, budget and risk.",
     "Руководил запуском и федеральным расширением сети EUROREPAR Car Service «под ключ», координируя региональных менеджеров, маркетинг, операции и внешних партнёров. Формировал бизнес-требования к CRM, сайту и системам лидогенерации, вёл проекты цифровой трансформации сети и управлял онбордингом партнёров, обучением, KPI, бюджетом и рисками.",
     "Built ~300 service centres from scratch · grew sales from zero to ~RUB 100M in three years · helped move Russia from 28th to 2nd place globally for the brand.",
     "Построил ~300 сервисных центров с нуля · вывел продажи с нуля до ~100 млн ₽ за три года · помог поднять Россию с 28-го на 2-е место в мире по бренду.", False),
    ("2016 – 2018", "2016 – 2018", "CarFix",
     "Head of Sales / Business Development", "Директор по продажам / развитию бизнеса",
     "Joined an early-stage technology startup and helped transform the business idea into a scalable digital platform — building the sales organisation from scratch, working directly with software engineers to define CRM and automation requirements, managing the backlog in Jira, and introducing KPI-driven reporting and quality metrics.",
     "Присоединился к технологическому стартапу на ранней стадии и помог превратить идею в масштабируемую цифровую платформу — построил отдел продаж с нуля, работал напрямую с разработчиками над требованиями к CRM и автоматизации, вёл бэклог в Jira и внедрил отчётность и метрики качества на основе KPI.",
     "Contributed to strategic planning and investor presentations as the platform scaled.",
     "Участвовал в стратегическом планировании и презентациях для инвесторов по мере роста платформы.", False),
    ("2009 – 2016", "2009 – 2016", "ARC Europe / ADAC Group",
     "Head of Operations", "Директор по операциям",
     "Built and managed large-scale operational infrastructure and service delivery, including CRM/ERP implementation, budgeting, vendor management and process design across a cross-functional transformation programme.",
     "Построил и управлял крупной операционной инфраструктурой и сервисной доставкой, включая внедрение CRM/ERP, бюджетирование, управление подрядчиками и проектирование процессов в рамках кросс-функциональной программы трансформации.",
     "", "", False),
    ("Earlier career", "Ранние этапы карьеры", "Citibank · Dexia Bank · Renaissance Insurance · Beeline",
     "Sales, Operations & Customer Experience", "Продажи, операции и клиентский опыт",
     "Roles spanning sales, business development, process improvement, customer experience, KPI reporting, stakeholder coordination and operational transformation across banking, insurance and telecom.",
     "Роли в продажах, развитии бизнеса, улучшении процессов, клиентском опыте, отчётности по KPI, координации стейкхолдеров и операционной трансформации в банкинге, страховании и телекоме.",
     "", "", True),
]

CASE_STUDIES = [
    ("Automotive · Network Development", "Автомобильная отрасль · Развитие сети",
     "Building a nationwide service network", "Строительство сети сервисных центров федерального масштаба",
     "Launch a new automotive service brand nationwide with no existing sales, no advertising budget, and strong competition from global players.",
     "Запустить новый автомобильный сервисный бренд по всей стране без существующих продаж, без рекламного бюджета и в условиях сильной конкуренции с глобальными игроками.",
     "Defined the rollout model end-to-end — partner onboarding, training, CRM and lead-generation requirements — and coordinated regional managers, marketing and operations against a shared roadmap and KPI framework.",
     "Определил модель развёртывания «под ключ» — онбординг партнёров, обучение, требования к CRM и лидогенерации — и координировал региональных менеджеров, маркетинг и операции по единой дорожной карте и системе KPI.",
     "Grew the network to roughly 300 service centres and ~RUB 100M in new sales within three years, helping move Russia from 28th to 2nd place globally for the brand.",
     "Вырастил сеть примерно до 300 сервисных центров и ~100 млн ₽ новых продаж за три года, что помогло поднять Россию с 28-го на 2-е место в мире по бренду."),
    ("Startup · Commercial Operations", "Стартап · Коммерческие операции",
     "Building commercial operations for a digital startup", "Построение коммерческих операций для цифрового стартапа",
     "Turn an early-stage automotive-services idea into a working, scalable digital business with no existing sales organisation.",
     "Превратить идею на ранней стадии в сфере автоуслуг в работающий, масштабируемый цифровой бизнес без существующей структуры продаж.",
     "Built the sales function from scratch, worked directly with software engineers to define CRM and automation requirements, and introduced Agile-style collaboration and KPI reporting through Jira.",
     "Построил функцию продаж с нуля, работал напрямую с разработчиками над требованиями к CRM и автоматизации, внедрил Agile-подход к сотрудничеству и отчётность по KPI через Jira.",
     "Established a functioning commercial operation with structured reporting and quality metrics, supporting the company's strategic planning and investor presentations.",
     "Создал работающую коммерческую структуру со структурированной отчётностью и метриками качества, поддержав стратегическое планирование и презентации для инвесторов."),
    ("Operations · Digital Transformation", "Операции · Цифровая трансформация",
     "Operations and digital transformation", "Операции и цифровая трансформация",
     "Build large-scale operational infrastructure capable of reliable service delivery across a cross-functional organisation.",
     "Построить крупную операционную инфраструктуру, способную обеспечивать надёжную доставку сервиса в кросс-функциональной организации.",
     "Implemented CRM/ERP systems, redesigned core processes, and put budgeting, vendor management and KPI controls in place across the operation.",
     "Внедрил CRM/ERP-системы, пересобрал ключевые процессы и выстроил бюджетирование, управление подрядчиками и контроль по KPI в рамках всей операции.",
     "Delivered a stable, scalable operating model supporting service delivery and cross-functional transformation.",
     "Обеспечил стабильную, масштабируемую операционную модель, поддерживающую сервисную доставку и кросс-функциональную трансформацию."),
]

AUDIENCE = [
    ("CEOs & Founders", "Генеральные директора и основатели"),
    ("COOs", "Операционные директора"),
    ("Heads of Operations", "Руководители операций"),
    ("Product Leaders", "Продуктовые лидеры"),
    ("Transformation Leaders", "Лидеры трансформации"),
    ("SMEs", "Малый и средний бизнес"),
    ("Scale-ups", "Растущие компании"),
    ("International Technology Companies", "Международные технологические компании"),
    ("Companies Undergoing Digital Transformation", "Компании в процессе цифровой трансформации"),
    ("Individuals in Career Transition", "Специалисты в процессе смены карьеры"),
]
